#!/usr/bin/env python3
"""sKEY — edit KeebDeck colored keys (F1–F6) without keyd.

  python3 sKEY.py           editor
  python3 sKEY.py show
  python3 sKEY.py apply     tmux binds only (need tmux)
  python3 sKEY.py daemon    OS-level intercept (needs python3-evdev, root)
  python3 sKEY.py stop
"""

import curses
import curses.textpad
import json
import os
import shutil
import signal
import subprocess
import sys
import time

NAME = "sKEY"
CONFIG = os.path.expanduser("~/.skey.json")
TMUX = os.path.expanduser("~/.tmux.conf")
BEGIN = "# --- skey begin ---"
END = "# --- skey end ---"
PIDFILE = "/tmp/skey-daemon.pid"
MAPFILE = os.path.expanduser("~/.skey.map")
DUMPFILE = "/tmp/skey-dump.map"
CODE_BY_LINUX = {
    "KEY_F1": 59,
    "KEY_F2": 60,
    "KEY_F3": 61,
    "KEY_F4": 62,
    "KEY_F5": 63,
    "KEY_F6": 64,
}

KEYS = [
    ("red", "F1", "KEY_F1"),
    ("orange", "F2", "KEY_F2"),
    ("yellow", "F3", "KEY_F3"),
    ("green", "F4", "KEY_F4"),
    ("blue", "F5", "KEY_F5"),
    ("purple", "F6", "KEY_F6"),
]

ACTIONS = ("none", "cmd", "tmux")

DEFAULTS = {
    "red": {"action": "none", "cmd": "", "note": "leave as extra F1"},
    "orange": {"action": "none", "cmd": "", "note": ""},
    "yellow": {"action": "none", "cmd": "", "note": ""},
    "green": {"action": "none", "cmd": "", "note": ""},
    "blue": {
        "action": "tmux",
        "cmd": "/home/working/SharkDeck/SharkDeck",
        "note": "new window in this dir",
    },
    "purple": {"action": "cmd", "cmd": "htop", "note": "htop in a new window"},
}


def load_cfg():
    cfg = {k: dict(v) for k, v in DEFAULTS.items()}
    if os.path.exists(CONFIG):
        try:
            raw = json.load(open(CONFIG, encoding="utf-8"))
            if isinstance(raw, dict):
                for k, v in raw.items():
                    if k in cfg and isinstance(v, dict):
                        cfg[k].update(v)
        except (OSError, json.JSONDecodeError):
            pass
    return cfg


def save_cfg(cfg):
    tmp = CONFIG + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(cfg, fh, indent=2, sort_keys=True)
        fh.write("\n")
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, CONFIG)
    os.chmod(CONFIG, 0o600)


def tmux_lines(cfg):
    lines = [BEGIN, "# generated by sKEY — do not edit this block by hand"]
    for color, fk, _linux in KEYS:
        row = cfg.get(color, {})
        action = row.get("action", "none")
        cmd = (row.get("cmd") or "").replace("'", "'\"'\"'")
        if action == "none" or not cmd.strip():
            lines.append("# %s %s unused" % (color, fk))
            continue
        if action == "tmux":
            lines.append("bind-key -n %s new-window -c '%s'" % (fk, cmd))
        elif action == "cmd":
            lines.append("bind-key -n %s new-window '%s'" % (fk, cmd))
    lines.append(END)
    return "\n".join(lines) + "\n"


def apply_tmux(cfg):
    block = tmux_lines(cfg)
    existing = ""
    if os.path.exists(TMUX):
        existing = open(TMUX, encoding="utf-8").read()
    if BEGIN in existing and END in existing:
        pre = existing[: existing.index(BEGIN)]
        post = existing[existing.index(END) + len(END) :]
        if post.startswith("\n"):
            post = post[1:]
        text = pre + block + post
    else:
        if existing and not existing.endswith("\n"):
            existing += "\n"
        text = existing + block
    tmp = TMUX + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, TMUX)
    if shutil.which("tmux"):
        os.system("tmux source-file %s >/dev/null 2>&1" % TMUX)
    return TMUX


def prompt(stdscr, title, default=""):
    h, w = stdscr.getmaxyx()
    ph, pw = 5, min(w - 2, 52)
    y, x = max(0, h // 2 - 2), max(0, (w - pw) // 2)
    win = curses.newwin(ph, pw, y, x)
    win.bkgd(" ", curses.color_pair(2))
    win.box()
    win.addnstr(1, 2, title[: pw - 4], pw - 4)
    win.refresh()
    sub = win.derwin(1, pw - 4, 3, 2)
    try:
        sub.addstr(0, 0, default[: pw - 4])
    except curses.error:
        pass
    curses.curs_set(1)
    tb = curses.textpad.Textbox(sub)
    try:
        raw = tb.edit().strip()
    except KeyboardInterrupt:
        raw = default
    curses.curs_set(0)
    return raw


def draw(stdscr, cfg, cur, msg):
    h, w = stdscr.getmaxyx()
    stdscr.erase()
    stdscr.addnstr(0, 0, "sKEY  colored KeebDeck  (no keyd)", w, curses.color_pair(1) | curses.A_BOLD)
    stdscr.addnstr(1, 0, "Enter edit   a cycle action   s save+apply   q quit", w)
    for i, (color, fk, _linux) in enumerate(KEYS):
        row = cfg[color]
        line = "%-7s %s  %-5s  %s" % (color, fk, row.get("action", "none"), row.get("cmd", ""))
        attr = curses.color_pair(3) | curses.A_BOLD if i == cur else curses.A_NORMAL
        try:
            stdscr.addnstr(3 + i, 0, line[:w], w, attr)
        except curses.error:
            pass
    note = cfg[KEYS[cur][0]].get("note") or ""
    try:
        stdscr.addnstr(h - 3, 0, note[:w], w, curses.color_pair(2))
        stdscr.addnstr(h - 2, 0, "none=keep F-key   cmd=tmux new-window 'cmd'   tmux=new-window -c DIR", w)
        stdscr.addnstr(h - 1, 0, (msg or CONFIG)[:w], w, curses.color_pair(1))
    except curses.error:
        pass
    stdscr.refresh()


def ui(stdscr):
    curses.curs_set(0)
    curses.use_default_colors()
    if curses.has_colors():
        curses.start_color()
        curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLUE)
        curses.init_pair(2, curses.COLOR_WHITE, -1)
        curses.init_pair(3, curses.COLOR_BLACK, curses.COLOR_CYAN)
    cfg = load_cfg()
    cur = 0
    msg = "arrows move"
    while True:
        draw(stdscr, cfg, cur, msg)
        k = stdscr.getch()
        if k in (ord("q"), 27, curses.KEY_F10):
            break
        if k == curses.KEY_UP:
            cur = (cur - 1) % 6
        elif k == curses.KEY_DOWN:
            cur = (cur + 1) % 6
        elif k in (ord("a"), ord("A")):
            color = KEYS[cur][0]
            i = ACTIONS.index(cfg[color].get("action", "none"))
            cfg[color]["action"] = ACTIONS[(i + 1) % len(ACTIONS)]
            msg = "%s -> %s" % (color, cfg[color]["action"])
        elif k in (10, 13, curses.KEY_ENTER):
            color = KEYS[cur][0]
            cur_cmd = cfg[color].get("cmd", "")
            label = "command or directory for %s" % color
            typed = prompt(stdscr, label, cur_cmd)
            cfg[color]["cmd"] = typed
            if typed and cfg[color].get("action") == "none":
                if os.path.isdir(os.path.expanduser(typed)):
                    cfg[color]["action"] = "tmux"
                else:
                    cfg[color]["action"] = "cmd"
            msg = "%s set" % color
        elif k in (ord("s"), ord("S"), curses.KEY_F3):
            save_cfg(cfg)
            path = apply_tmux(cfg)
            msg = "saved tmux. run: python3 sKEY.py daemon"
        elif k in (ord("w"), ord("W")):
            save_cfg(cfg)
            msg = "saved %s" % CONFIG


def keymap_string(row):
    action = row.get("action", "none")
    cmd = (row.get("cmd") or "").strip()
    if action == "none" or not cmd:
        return None
    if action == "tmux":
        text = "tmux new-window -c %s" % cmd
    else:
        text = cmd
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == '"':
            out.append('\\"')
        else:
            out.append(ch)
    return "".join(out) + "\\n"


def cmd_console():
    cfg = load_cfg()
    if not shutil.which("loadkeys") or not shutil.which("dumpkeys"):
        print("need kbd package:  apt install -y kbd")
        return 2
    rc = os.system("dumpkeys > %s" % DUMPFILE)
    if rc != 0:
        print("dumpkeys failed (try sudo)")
        return 2
    extra = ["", "# sKEY colored keys"]
    # F70-F75 as string slots
    slot = 70
    for color, _fk, linux in KEYS:
        row = cfg.get(color) or {}
        s = keymap_string(row)
        code = CODE_BY_LINUX[linux]
        if not s:
            extra.append("# %s keycode %s unchanged" % (color, code))
            continue
        extra.append("keycode %d = F%d" % (code, slot))
        extra.append('string F%d = "%s"' % (slot, s))
        slot += 1
    text = open(DUMPFILE, encoding="utf-8", errors="replace").read()
    text = text + "\n" + "\n".join(extra) + "\n"
    with open(MAPFILE, "w", encoding="utf-8") as fh:
        fh.write(text)
    rc = os.system("loadkeys %s" % MAPFILE)
    if rc != 0:
        print("loadkeys failed (try sudo python3 sKEY.py console)")
        return 2
    print("loaded", MAPFILE)
    print("These keys now TYPE the command on this console.")
    print("Press blue/purple at a shell prompt to test.")
    return 0


def cmd_watch():
    try:
        from evdev import InputDevice, categorize, ecodes
    except ImportError:
        print("apt install -y python3-evdev")
        return 2
    print("devices:")
    by_id = "/dev/input/by-id"
    if os.path.isdir(by_id):
        for name in sorted(os.listdir(by_id)):
            print(" ", name, "->", os.path.realpath(os.path.join(by_id, name)))
    path = find_keeb()
    print("using", path)
    if not path:
        return 2
    dev = InputDevice(path)
    print(dev)
    print("press colored keys, Ctrl-C to stop. no grab.")
    for event in dev.read_loop():
        if event.type == ecodes.EV_KEY:
            print("code", event.code, "value", event.value, ecodes.KEY.get(event.code, "?"))


def find_keeb():
    by_id = "/dev/input/by-id"
    if os.path.isdir(by_id):
        for name in os.listdir(by_id):
            low = name.lower()
            if "keebdeck" in low or "solder_party" in low:
                if "event-kbd" in low or "event" in low:
                    return os.path.realpath(os.path.join(by_id, name))
    return None


def fire(color, row):
    action = row.get("action", "none")
    cmd = (row.get("cmd") or "").strip()
    if action == "none" or not cmd:
        return
    if action == "tmux":
        if shutil.which("tmux"):
            subprocess.Popen(["tmux", "new-window", "-c", cmd])
        else:
            subprocess.Popen(["bash", "-lc", "cd %s && exec bash" % cmd], start_new_session=True)
        return
    if shutil.which("tmux"):
        subprocess.Popen(["tmux", "new-window", cmd])
    else:
        subprocess.Popen(cmd, shell=True, start_new_session=True)


def swallow_map(cfg):
    out = {}
    for color, _fk, linux in KEYS:
        row = cfg.get(color) or {}
        if row.get("action", "none") != "none" and (row.get("cmd") or "").strip():
            out[CODE_BY_LINUX[linux]] = (color, row)
    return out


def write_pid():
    with open(PIDFILE, "w") as fh:
        fh.write(str(os.getpid()))


def read_pid():
    try:
        return int(open(PIDFILE).read().strip())
    except (OSError, ValueError):
        return None


def cmd_stop():
    pid = read_pid()
    if not pid:
        print("sKEY daemon not running")
        return 0
    try:
        os.kill(pid, signal.SIGTERM)
        time.sleep(0.3)
        print("stopped", pid)
    except OSError as exc:
        print("stop failed:", exc)
    try:
        os.remove(PIDFILE)
    except OSError:
        pass
    return 0


def cmd_daemon():
    try:
        from evdev import InputDevice, UInput, ecodes
    except ImportError:
        print("need python3-evdev:")
        print("  apt install -y python3-evdev")
        return 2
    cfg = load_cfg()
    path = find_keeb()
    if not path:
        print("KeebDeck not found under /dev/input/by-id")
        print("ls /dev/input/by-id/")
        return 2
    grabbed = {}
    intercept = swallow_map(cfg)
    print("sKEY daemon")
    print("device", path)
    print("intercept", sorted(CODE_BY_LINUX[k[2]] for k in KEYS if CODE_BY_LINUX[k[2]] in intercept))
    write_pid()
    src = InputDevice(path)
    ui = UInput.from_device(src, name="sKEY-forward")
    try:
        src.grab()
        grabbed["src"] = True
        for event in src.read_loop():
            if event.type == ecodes.EV_KEY and event.code in intercept:
                if event.value == 1:
                    color, row = intercept[event.code]
                    fire(color, row)
                continue
            ui.write_event(event)
    except KeyboardInterrupt:
        print("stopped")
    finally:
        try:
            src.ungrab()
        except Exception:
            pass
        ui.close()
        try:
            os.remove(PIDFILE)
        except OSError:
            pass
    return 0


def show(cfg):
    print(NAME)
    print("config", CONFIG)
    for color, fk, linux in KEYS:
        row = cfg[color]
        print("%-7s %s %-6s %s" % (color, fk, row.get("action"), row.get("cmd", "")))
    print()
    print(tmux_lines(cfg))


def main():
    cfg = load_cfg()
    arg = sys.argv[1] if len(sys.argv) > 1 else "ui"
    if arg in ("-h", "--help", "help"):
        print("sKEY.py [ui|show|apply|console|watch|daemon|stop]")
        print("console = loadkeys (changes what the TTY types)  << use this")
        print("watch   = print raw key codes, no grab")
        print("daemon  = evdev intercept + uinput")
        print("apply   = tmux binds only")
        return 0
    if arg == "show":
        show(cfg)
        return 0
    if arg == "apply":
        save_cfg(cfg)
        print(apply_tmux(cfg))
        print("tmux only. For OS-wide keys: python3 sKEY.py daemon")
        return 0
    if arg == "daemon":
        return cmd_daemon()
    if arg == "stop":
        return cmd_stop()
    if arg == "console":
        return cmd_console()
    if arg == "watch":
        return cmd_watch()
    if not sys.stdout.isatty():
        print("sKEY UI needs a tty. Use: python3 sKEY.py show")
        return 2
    curses.wrapper(ui)
    return 0


if __name__ == "__main__":
    sys.exit(main())
