# Version 1.0
#!/usr/bin/env python3
# sKeys — edit KeebDeck colored keys (F1–F6) without keyd.

# Curses editor + writes a marked block into ~/.tmux.conf
# Never grabs /dev/input. Never starts keyd.

#  python3 skeys.py
#  python3 skeys.py apply
#  python3 skeys.py show


import curses
import curses.textpad
import json
import os
import shutil
import sys

NAME = "sKeys"
CONFIG = os.path.expanduser("~/.skeys.json")
TMUX = os.path.expanduser("~/.tmux.conf")
BEGIN = "# --- skeys begin ---"
END = "# --- skeys end ---"

KEYS = [
    ("red", "F1", "KEY_F1"),
    ("orange", "F2", "KEY_F2"),
    ("yellow", "F3", "KEY_F3"),
    ("green", "F4", "KEY_F4"),
    ("blue", "F5", "KEY_F5"),
    ("purple", "F6", "KEY_F6"),
]

ACTIONS = ("none", "cmd", "tmux")

DEFAULTS = {
    "red": {"action": "none", "cmd": "", "note": "leave as extra F1"},
    "orange": {"action": "none", "cmd": "", "note": ""},
    "yellow": {"action": "none", "cmd": "", "note": ""},
    "green": {"action": "none", "cmd": "", "note": ""},
    "blue": {
        "action": "tmux",
        "cmd": "/home/working/SharkDeck/SharkDeck",
        "note": "new window in this dir",
    },
    "purple": {"action": "cmd", "cmd": "htop", "note": "htop in a new window"},
}


def load_cfg():
    cfg = {k: dict(v) for k, v in DEFAULTS.items()}
    if os.path.exists(CONFIG):
        try:
            raw = json.load(open(CONFIG, encoding="utf-8"))
            if isinstance(raw, dict):
                for k, v in raw.items():
                    if k in cfg and isinstance(v, dict):
                        cfg[k].update(v)
        except (OSError, json.JSONDecodeError):
            pass
    return cfg


def save_cfg(cfg):
    tmp = CONFIG + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(cfg, fh, indent=2, sort_keys=True)
        fh.write("\n")
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, CONFIG)
    os.chmod(CONFIG, 0o600)


def tmux_lines(cfg):
    lines = [BEGIN, "# generated by sKeys — do not edit this block by hand"]
    for color, fk, _linux in KEYS:
        row = cfg.get(color, {})
        action = row.get("action", "none")
        cmd = (row.get("cmd") or "").replace("'", "'\"'\"'")
        if action == "none" or not cmd.strip():
            lines.append("# %s %s unused" % (color, fk))
            continue
        if action == "tmux":
            lines.append("bind-key -n %s new-window -c '%s'" % (fk, cmd))
        elif action == "cmd":
            lines.append("bind-key -n %s new-window '%s'" % (fk, cmd))
    lines.append(END)
    return "\n".join(lines) + "\n"


def apply_tmux(cfg):
    block = tmux_lines(cfg)
    existing = ""
    if os.path.exists(TMUX):
        existing = open(TMUX, encoding="utf-8").read()
    if BEGIN in existing and END in existing:
        pre = existing[: existing.index(BEGIN)]
        post = existing[existing.index(END) + len(END) :]
        if post.startswith("\n"):
            post = post[1:]
        text = pre + block + post
    else:
        if existing and not existing.endswith("\n"):
            existing += "\n"
        text = existing + block
    tmp = TMUX + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, TMUX)
    if shutil.which("tmux"):
        os.system("tmux source-file %s >/dev/null 2>&1" % TMUX)
    return TMUX


def prompt(stdscr, title, default=""):
    h, w = stdscr.getmaxyx()
    ph, pw = 5, min(w - 2, 52)
    y, x = max(0, h // 2 - 2), max(0, (w - pw) // 2)
    win = curses.newwin(ph, pw, y, x)
    win.bkgd(" ", curses.color_pair(2))
    win.box()
    win.addnstr(1, 2, title[: pw - 4], pw - 4)
    win.refresh()
    sub = win.derwin(1, pw - 4, 3, 2)
    try:
        sub.addstr(0, 0, default[: pw - 4])
    except curses.error:
        pass
    curses.curs_set(1)
    tb = curses.textpad.Textbox(sub)
    try:
        raw = tb.edit().strip()
    except KeyboardInterrupt:
        raw = default
    curses.curs_set(0)
    return raw


def draw(stdscr, cfg, cur, msg):
    h, w = stdscr.getmaxyx()
    stdscr.erase()
    stdscr.addnstr(0, 0, "sKeys  colored KeebDeck  (no keyd)", w, curses.color_pair(1) | curses.A_BOLD)
    stdscr.addnstr(1, 0, "Enter edit   a cycle action   s save+apply   q quit", w)
    for i, (color, fk, _linux) in enumerate(KEYS):
        row = cfg[color]
        line = "%-7s %s  %-5s  %s" % (color, fk, row.get("action", "none"), row.get("cmd", ""))
        attr = curses.color_pair(3) | curses.A_BOLD if i == cur else curses.A_NORMAL
        try:
            stdscr.addnstr(3 + i, 0, line[:w], w, attr)
        except curses.error:
            pass
    note = cfg[KEYS[cur][0]].get("note") or ""
    try:
        stdscr.addnstr(h - 3, 0, note[:w], w, curses.color_pair(2))
        stdscr.addnstr(h - 2, 0, "none=keep F-key   cmd=tmux new-window 'cmd'   tmux=new-window -c DIR", w)
        stdscr.addnstr(h - 1, 0, (msg or CONFIG)[:w], w, curses.color_pair(1))
    except curses.error:
        pass
    stdscr.refresh()


def ui(stdscr):
    curses.curs_set(0)
    curses.use_default_colors()
    if curses.has_colors():
        curses.start_color()
        curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLUE)
        curses.init_pair(2, curses.COLOR_WHITE, -1)
        curses.init_pair(3, curses.COLOR_BLACK, curses.COLOR_CYAN)
    cfg = load_cfg()
    cur = 0
    msg = "arrows move"
    while True:
        draw(stdscr, cfg, cur, msg)
        k = stdscr.getch()
        if k in (ord("q"), 27, curses.KEY_F10):
            break
        if k == curses.KEY_UP:
            cur = (cur - 1) % 6
        elif k == curses.KEY_DOWN:
            cur = (cur + 1) % 6
        elif k in (ord("a"), ord("A")):
            color = KEYS[cur][0]
            i = ACTIONS.index(cfg[color].get("action", "none"))
            cfg[color]["action"] = ACTIONS[(i + 1) % len(ACTIONS)]
            msg = "%s -> %s" % (color, cfg[color]["action"])
        elif k in (10, 13, curses.KEY_ENTER):
            color = KEYS[cur][0]
            cur_cmd = cfg[color].get("cmd", "")
            label = "command or directory for %s" % color
            typed = prompt(stdscr, label, cur_cmd)
            cfg[color]["cmd"] = typed
            if typed and cfg[color].get("action") == "none":
                if os.path.isdir(os.path.expanduser(typed)):
                    cfg[color]["action"] = "tmux"
                else:
                    cfg[color]["action"] = "cmd"
            msg = "%s set" % color
        elif k in (ord("s"), ord("S"), curses.KEY_F3):
            save_cfg(cfg)
            path = apply_tmux(cfg)
            msg = "saved + applied %s  (need tmux)" % path
        elif k in (ord("w"), ord("W")):
            save_cfg(cfg)
            msg = "saved %s" % CONFIG


def show(cfg):
    print(NAME)
    print("config", CONFIG)
    for color, fk, linux in KEYS:
        row = cfg[color]
        print("%-7s %s %-6s %s" % (color, fk, row.get("action"), row.get("cmd", "")))
    print()
    print(tmux_lines(cfg))


def main():
    cfg = load_cfg()
    arg = sys.argv[1] if len(sys.argv) > 1 else "ui"
    if arg in ("-h", "--help", "help"):
        print("skeys.py [ui|show|apply]")
        print("Colored keys are F1-F6. This writes tmux binds only.")
        print("keyd is not used.")
        return 0
    if arg == "show":
        show(cfg)
        return 0
    if arg == "apply":
        save_cfg(cfg)
        print(apply_tmux(cfg))
        print("If you are in tmux: binds are live. Else: tmux new -s deck")
        return 0
    if not sys.stdout.isatty():
        print("sKeys UI needs a tty. Use: python3 skeys.py show")
        return 2
    curses.wrapper(ui)
    return 0


if __name__ == "__main__":
    sys.exit(main())
